package net.informatikag.thomapp

import android.os.Bundle
import android.view.Menu
import com.google.android.material.snackbar.Snackbar
import com.google.android.material.navigation.NavigationView
import androidx.navigation.findNavController
import androidx.navigation.ui.AppBarConfiguration
import androidx.navigation.ui.navigateUp
import androidx.navigation.ui.setupActionBarWithNavController
import androidx.navigation.ui.setupWithNavController
import androidx.drawerlayout.widget.DrawerLayout
import androidx.appcompat.app.AppCompatActivity
import net.informatikag.thomapp.databinding.ActivityMainBinding

/**
 * This was mostly auto generated by Android Studio
 */
class MainActivity : AppCompatActivity(){

    private lateinit var appBarConfiguration: AppBarConfiguration
    private lateinit var binding: ActivityMainBinding

    companion object {
        val ARTICLES_PER_PAGE: Int = 10
        val WORDPRESS_BASE_URL_LITE: String = "https://thoms-line.thomaeum.de/wp-json/wp/v2/posts?_embed=wp:featuredmedia&_fields=id,title.rendered, excerpt.rendered, _links, _embedded"
        val WORDPRESS_BASE_URL_FULL: String = "https://thoms-line.thomaeum.de/wp-json/wp/v2/posts?_embed"
        val THOMSLINE_LIST_ARTICLE_PADDING: Int = 30
        val VERTRETUNGSPLAN_OBERSTUFE_PDF: String = "https://thomaeum.de/wp-content/uploads/2020/10/thom2.pdf"
        val VERTRETUNGSPLAN_UNTERSTUFE_PDF: String = "https://thomaeum.de/wp-content/uploads/2020/10/thom_si.pdf"
    }

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        binding = ActivityMainBinding.inflate(layoutInflater)
        setContentView(binding.root)

        setSupportActionBar(binding.appBarMain.toolbar)

        val drawerLayout: DrawerLayout = binding.drawerLayout
        val navView: NavigationView = binding.navView
        val navController = findNavController(R.id.nav_host_fragment_content_main)
        // Passing each menu ID as a set of Ids because each
        // menu should be considered as top level destinations.
        appBarConfiguration = AppBarConfiguration(
            setOf(
                R.id.nav_home, R.id.nav_thomsline, R.id.nav_vertretungsplan_oberstufe, R.id.nav_vertretungsplan_unterstufe
            ), drawerLayout
        )
        setupActionBarWithNavController(navController, appBarConfiguration)
        navView.setupWithNavController(navController)
    }

    override fun onCreateOptionsMenu(menu: Menu): Boolean {
        // Inflate the menu; this adds items to the action bar if it is present.
        menuInflater.inflate(R.menu.main, menu)
        return true
    }

    override fun onSupportNavigateUp(): Boolean {
        val navController = findNavController(R.id.nav_host_fragment_content_main)
        return navController.navigateUp(appBarConfiguration) || super.onSupportNavigateUp()
    }
}